# Generated by Django 5.0.4 on 2024-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee_Data",
            fields=[
                ("c_ID", models.CharField(max_length=20, unique=True)),
                ("c_FirstName", models.CharField(max_length=225)),
                ("c_Lastname", models.CharField(max_length=225)),
                ("c_Role", models.CharField(max_length=225)),
                ("c_address", models.CharField(max_length=225)),
                ("c_Email", models.CharField(max_length=225)),
                ("c_Phone", models.CharField(max_length=225)),
                ("c_Informarion", models.CharField(max_length=225)),
            ],
            options={
                "db_table": "EmployeeData",
            },
        ),
    ]
