# Generated by Django 5.0.4 on 2024-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee_data",
            name="c_ID",
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
    ]
