# Generated by Django 5.0.4 on 2024-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_employee_data_c_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=225)),
                ("Last_Name", models.CharField(max_length=225)),
                ("Emai", models.CharField(max_length=225)),
                ("Password", models.CharField(max_length=225)),
            ],
            options={
                "db_table": "UsersData",
            },
        ),
    ]
